language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - 'node'
  - '6'
before_install:
  - npm i -g npm@5
script:
  - npm run test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
